/**
 * Curated dataset of disc golf courses in Norway.
 * Sources: UDisc, PDGA, Disc Golf Scene, community data.
 *
 * Each course includes:
 *  - name: Course name
 *  - lat/lng: GPS coordinates
 *  - city: Nearest city/town
 *  - region: Norwegian region/county
 *  - holes: Number of holes (main layout)
 *  - rating: Approximate rating out of 5 (from UDisc/community)
 *  - reviews: Approximate number of reviews
 *  - difficulty: "Easy", "Moderate", "Hard", "Very Hard"
 *  - description: Short description
 *  - udisc: UDisc URL (where available)
 */
const COURSES = [
  // === Østlandet (Eastern Norway) ===
  {
    name: "Krokhol Disc Golf Course",
    lat: 59.7267,
    lng: 10.8500,
    city: "Siggerud",
    region: "Viken",
    holes: 18,
    rating: 4.8,
    reviews: 2200,
    difficulty: "Very Hard",
    description: "World-class championship course, ranked among the top disc golf courses globally. Beautiful forest terrain with technical shots.",
    udisc: "https://udisc.com/courses/krokhol-disc-golf-course-bDYw"
  },
  {
    name: "Ekeberg Discgolfpark",
    lat: 59.8983,
    lng: 10.7744,
    city: "Oslo",
    region: "Oslo",
    holes: 18,
    rating: 3.9,
    reviews: 1100,
    difficulty: "Moderate",
    description: "Popular urban course in Oslo with great views of the city and Oslofjord.",
    udisc: "https://udisc.com/courses/ekeberg-discgolfpark-VDzU"
  },
  {
    name: "Stovner DiskGolfPark",
    lat: 59.9617,
    lng: 10.9233,
    city: "Oslo",
    region: "Oslo",
    holes: 18,
    rating: 3.7,
    reviews: 650,
    difficulty: "Moderate",
    description: "One of Oslo's most established courses, founded in 1994. Nice wooded terrain.",
    udisc: "https://udisc.com/courses/stovner-diskgolfpark-bN8L"
  },
  {
    name: "Muselunden Discgolfpark",
    lat: 59.9283,
    lng: 10.7017,
    city: "Oslo",
    region: "Oslo",
    holes: 9,
    rating: 3.3,
    reviews: 400,
    difficulty: "Easy",
    description: "Beginner-friendly 9-hole course in central Oslo. Great for newcomers to the sport.",
    udisc: "https://udisc.com/courses/muselunden-discgolfpark-qn7F"
  },
  {
    name: "Holmenkollen Discgolfpark",
    lat: 59.9633,
    lng: 10.6667,
    city: "Oslo",
    region: "Oslo",
    holes: 18,
    rating: 3.8,
    reviews: 520,
    difficulty: "Moderate",
    description: "Scenic course near the famous Holmenkollen ski jump. Hilly terrain with varied shots.",
    udisc: "https://udisc.com/courses/holmenkollen-discgolfpark-ePDJ"
  },
  {
    name: "Løvbergsmoen Diskgolfpark",
    lat: 60.8700,
    lng: 11.5700,
    city: "Elverum",
    region: "Innlandet",
    holes: 27,
    rating: 4.5,
    reviews: 800,
    difficulty: "Hard",
    description: "Large 27-hole course in beautiful forest near Elverum. One of Norway's top courses.",
    udisc: "https://udisc.com/courses/lovbergsmoen-diskgolfpark-YxS5"
  },
  {
    name: "Christiansfjelds Frisbee Park",
    lat: 60.8817,
    lng: 11.5633,
    city: "Elverum",
    region: "Innlandet",
    holes: 18,
    rating: 3.6,
    reviews: 250,
    difficulty: "Moderate",
    description: "Enjoyable course in Elverum with a mix of open and wooded holes.",
    udisc: ""
  },
  {
    name: "Valdres Discgolfpark",
    lat: 61.0833,
    lng: 9.5000,
    city: "Leira i Valdres",
    region: "Innlandet",
    holes: 18,
    rating: 4.6,
    reviews: 1617,
    difficulty: "Hard",
    description: "Stunning mountain scenery course in Valdres. One of Norway's highest-rated courses with challenging technical holes.",
    udisc: "https://udisc.com/courses/valdres-discgolfpark-Oq4C"
  },
  {
    name: "Karidalen Frisbeegolfpark",
    lat: 60.6933,
    lng: 10.8317,
    city: "Lena",
    region: "Innlandet",
    holes: 18,
    rating: 4.7,
    reviews: 600,
    difficulty: "Hard",
    description: "Beautiful course near Lena in Innlandet. Consistently rated among Norway's best.",
    udisc: ""
  },
  {
    name: "Høytorp Discgolfpark",
    lat: 59.5500,
    lng: 11.3167,
    city: "Mysen",
    region: "Viken",
    holes: 18,
    rating: 4.2,
    reviews: 450,
    difficulty: "Hard",
    description: "Great course near Mysen with challenging wooded terrain and elevation changes.",
    udisc: ""
  },
  {
    name: "Hestehagen Diskgolfbane",
    lat: 59.2700,
    lng: 10.4150,
    city: "Tønsberg",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 4.4,
    reviews: 550,
    difficulty: "Very Hard",
    description: "Technical course near Tønsberg known for its demanding layout and beautiful surroundings.",
    udisc: ""
  },
  {
    name: "Kodal Disc Golf Course",
    lat: 59.2100,
    lng: 10.1700,
    city: "Kodal",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 4.3,
    reviews: 380,
    difficulty: "Moderate",
    description: "Well-maintained course in Kodal with a good mix of open and technical holes.",
    udisc: ""
  },
  {
    name: "Sandefjord Discgolfpark",
    lat: 59.1317,
    lng: 10.2167,
    city: "Sandefjord",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 3.8,
    reviews: 320,
    difficulty: "Moderate",
    description: "Popular course in the Sandefjord area with varied terrain.",
    udisc: ""
  },
  {
    name: "Larvik Discgolfpark",
    lat: 59.0500,
    lng: 10.0333,
    city: "Larvik",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 3.7,
    reviews: 280,
    difficulty: "Moderate",
    description: "Enjoyable course near Larvik with scenic coastal views.",
    udisc: ""
  },
  {
    name: "Drammen Discgolfpark",
    lat: 59.7500,
    lng: 10.2000,
    city: "Drammen",
    region: "Viken",
    holes: 18,
    rating: 3.8,
    reviews: 400,
    difficulty: "Moderate",
    description: "Well-designed course in the Drammen area.",
    udisc: ""
  },
  {
    name: "Kongsberg Discgolfpark",
    lat: 59.6633,
    lng: 9.6500,
    city: "Kongsberg",
    region: "Viken",
    holes: 18,
    rating: 3.9,
    reviews: 350,
    difficulty: "Moderate",
    description: "Scenic course near Kongsberg with elevation changes and forest terrain.",
    udisc: ""
  },
  {
    name: "Fredrikstad Discgolfpark",
    lat: 59.2200,
    lng: 10.9300,
    city: "Fredrikstad",
    region: "Viken",
    holes: 18,
    rating: 3.6,
    reviews: 270,
    difficulty: "Moderate",
    description: "Popular course in the Fredrikstad area.",
    udisc: ""
  },
  {
    name: "Halden Discgolfbane",
    lat: 59.1217,
    lng: 11.3867,
    city: "Halden",
    region: "Viken",
    holes: 18,
    rating: 3.5,
    reviews: 200,
    difficulty: "Moderate",
    description: "Course in Halden near the Swedish border.",
    udisc: ""
  },
  {
    name: "Lillehammer Discgolfpark",
    lat: 61.1150,
    lng: 10.4667,
    city: "Lillehammer",
    region: "Innlandet",
    holes: 18,
    rating: 4.0,
    reviews: 350,
    difficulty: "Moderate",
    description: "Beautiful course in the Olympic city of Lillehammer with mountain views.",
    udisc: ""
  },
  {
    name: "Hamar Discgolfpark",
    lat: 60.7945,
    lng: 11.0678,
    city: "Hamar",
    region: "Innlandet",
    holes: 18,
    rating: 3.7,
    reviews: 280,
    difficulty: "Moderate",
    description: "Well-maintained course near Hamar by Lake Mjøsa.",
    udisc: ""
  },
  {
    name: "Gjøvik Discgolfbane",
    lat: 60.7960,
    lng: 10.6920,
    city: "Gjøvik",
    region: "Innlandet",
    holes: 18,
    rating: 3.6,
    reviews: 220,
    difficulty: "Moderate",
    description: "Popular course by Mjøsa in Gjøvik.",
    udisc: ""
  },
  {
    name: "Moss Discgolfpark",
    lat: 59.4350,
    lng: 10.6550,
    city: "Moss",
    region: "Viken",
    holes: 18,
    rating: 3.7,
    reviews: 300,
    difficulty: "Moderate",
    description: "Nice course in Moss, convenient stop between Oslo and the south coast.",
    udisc: ""
  },
  {
    name: "Ski Discgolfpark",
    lat: 59.7183,
    lng: 10.8383,
    city: "Ski",
    region: "Viken",
    holes: 18,
    rating: 3.6,
    reviews: 250,
    difficulty: "Moderate",
    description: "Accessible course near Ski, south of Oslo.",
    udisc: ""
  },

  // === Sørlandet (Southern Norway) ===
  {
    name: "Sukkevann Frisbeegolfbane",
    lat: 58.1400,
    lng: 8.0100,
    city: "Kristiansand",
    region: "Agder",
    holes: 18,
    rating: 4.0,
    reviews: 400,
    difficulty: "Moderate",
    description: "Popular course in Kristiansand by a beautiful lake. Good variety of holes.",
    udisc: ""
  },
  {
    name: "Bølgane Discgolfbane",
    lat: 58.1533,
    lng: 8.0433,
    city: "Kristiansand",
    region: "Agder",
    holes: 9,
    rating: 3.5,
    reviews: 180,
    difficulty: "Easy",
    description: "Beginner-friendly course in Kristiansand.",
    udisc: ""
  },
  {
    name: "Arendal Discgolfpark",
    lat: 58.4617,
    lng: 8.7717,
    city: "Arendal",
    region: "Agder",
    holes: 18,
    rating: 3.8,
    reviews: 250,
    difficulty: "Moderate",
    description: "Nice coastal course near Arendal.",
    udisc: ""
  },
  {
    name: "Grimstad Discgolfbane",
    lat: 58.3400,
    lng: 8.5933,
    city: "Grimstad",
    region: "Agder",
    holes: 18,
    rating: 3.6,
    reviews: 180,
    difficulty: "Moderate",
    description: "Enjoyable course in the charming coastal town of Grimstad.",
    udisc: ""
  },

  // === Vestlandet (Western Norway) ===
  {
    name: "Kaupanger Frisbeepark",
    lat: 61.1833,
    lng: 7.2333,
    city: "Kaupanger",
    region: "Vestland",
    holes: 18,
    rating: 4.4,
    reviews: 500,
    difficulty: "Hard",
    description: "Scenic course in Sogn with fjord and mountain views. One of western Norway's best.",
    udisc: ""
  },
  {
    name: "Kulleseid Frisbeegolfbane",
    lat: 59.8333,
    lng: 5.2167,
    city: "Finnås",
    region: "Vestland",
    holes: 18,
    rating: 4.5,
    reviews: 350,
    difficulty: "Hard",
    description: "Top-rated course near Finnås with island scenery and challenging holes.",
    udisc: ""
  },
  {
    name: "Flaktveit Discgolfpark",
    lat: 60.4367,
    lng: 5.3633,
    city: "Bergen",
    region: "Vestland",
    holes: 18,
    rating: 3.8,
    reviews: 400,
    difficulty: "Moderate",
    description: "The main disc golf course in the Bergen area with varied terrain.",
    udisc: ""
  },
  {
    name: "Bergen Frisbeegolfbane",
    lat: 60.3830,
    lng: 5.3330,
    city: "Bergen",
    region: "Vestland",
    holes: 9,
    rating: 3.4,
    reviews: 250,
    difficulty: "Easy",
    description: "Central Bergen course, good for beginners and quick rounds.",
    udisc: ""
  },
  {
    name: "Jemtegård Disk Golf Bane",
    lat: 62.2000,
    lng: 7.0833,
    city: "Valldal",
    region: "Møre og Romsdal",
    holes: 18,
    rating: 4.4,
    reviews: 300,
    difficulty: "Hard",
    description: "Beautiful mountain course in Valldal with dramatic scenery and challenging shots.",
    udisc: ""
  },
  {
    name: "Øverås Diskgolfpark",
    lat: 62.5683,
    lng: 6.8167,
    city: "Vestnes",
    region: "Møre og Romsdal",
    holes: 35,
    rating: 4.6,
    reviews: 450,
    difficulty: "Very Hard",
    description: "Massive 35-hole course near Vestnes, famous for having one of the world's hardest holes.",
    udisc: ""
  },
  {
    name: "Ålesund Discgolfpark",
    lat: 62.4722,
    lng: 6.1549,
    city: "Ålesund",
    region: "Møre og Romsdal",
    holes: 18,
    rating: 3.9,
    reviews: 320,
    difficulty: "Moderate",
    description: "Popular course near the art nouveau city of Ålesund.",
    udisc: ""
  },
  {
    name: "Molde Discgolfpark",
    lat: 62.7350,
    lng: 7.1600,
    city: "Molde",
    region: "Møre og Romsdal",
    holes: 18,
    rating: 3.7,
    reviews: 250,
    difficulty: "Moderate",
    description: "Course in the 'City of Roses' with mountain panorama views.",
    udisc: ""
  },
  {
    name: "Kristiansund Discgolfbane",
    lat: 63.1100,
    lng: 7.7300,
    city: "Kristiansund",
    region: "Møre og Romsdal",
    holes: 18,
    rating: 3.6,
    reviews: 180,
    difficulty: "Moderate",
    description: "Coastal course in Kristiansund.",
    udisc: ""
  },
  {
    name: "Sola Frisbeegolfbane",
    lat: 58.8833,
    lng: 5.6000,
    city: "Sola",
    region: "Rogaland",
    holes: 18,
    rating: 3.9,
    reviews: 350,
    difficulty: "Moderate",
    description: "Course near Stavanger airport in Sola. Coastal terrain with wind challenges.",
    udisc: ""
  },
  {
    name: "Egeland Disc Golf Course",
    lat: 58.9467,
    lng: 5.7333,
    city: "Stavanger",
    region: "Rogaland",
    holes: 18,
    rating: 3.7,
    reviews: 280,
    difficulty: "Moderate",
    description: "Course near Stavanger with a mix of open and technical holes.",
    udisc: ""
  },
  {
    name: "Haugesund Discgolfpark",
    lat: 59.4133,
    lng: 5.2700,
    city: "Haugesund",
    region: "Rogaland",
    holes: 18,
    rating: 3.8,
    reviews: 220,
    difficulty: "Moderate",
    description: "Course in the Haugesund area with coastal terrain.",
    udisc: ""
  },
  {
    name: "Førde Discgolfpark",
    lat: 61.4517,
    lng: 5.8567,
    city: "Førde",
    region: "Vestland",
    holes: 18,
    rating: 3.7,
    reviews: 200,
    difficulty: "Moderate",
    description: "Scenic course in the Sunnfjord region.",
    udisc: ""
  },
  {
    name: "Sogndal Discgolfbane",
    lat: 61.2300,
    lng: 7.0933,
    city: "Sogndal",
    region: "Vestland",
    holes: 18,
    rating: 4.0,
    reviews: 280,
    difficulty: "Moderate",
    description: "Beautiful course near Sogndal with fjord and mountain scenery.",
    udisc: ""
  },
  {
    name: "Voss Discgolfpark",
    lat: 60.6283,
    lng: 6.4200,
    city: "Voss",
    region: "Vestland",
    holes: 18,
    rating: 4.0,
    reviews: 260,
    difficulty: "Moderate",
    description: "Course near the adventure capital Voss, surrounded by mountains.",
    udisc: ""
  },
  {
    name: "Stord Discgolfbane",
    lat: 59.7783,
    lng: 5.5100,
    city: "Stord",
    region: "Vestland",
    holes: 18,
    rating: 3.6,
    reviews: 180,
    difficulty: "Moderate",
    description: "Island course on Stord with nice variety.",
    udisc: ""
  },

  // === Trøndelag (Central Norway) ===
  {
    name: "Glåmos Diskgolfbane",
    lat: 62.7550,
    lng: 11.6567,
    city: "Glåmos",
    region: "Trøndelag",
    holes: 34,
    rating: 4.7,
    reviews: 958,
    difficulty: "Hard",
    description: "Norway's highest-rated course on UDisc! A massive 34-hole experience in beautiful mountain terrain. Must-play destination.",
    udisc: "https://udisc.com/courses/glamos-diskgolfbane-EhEv"
  },
  {
    name: "Ørland Discgolfpark",
    lat: 63.6883,
    lng: 9.6083,
    city: "Brekstad",
    region: "Trøndelag",
    holes: 18,
    rating: 4.6,
    reviews: 1124,
    difficulty: "Hard",
    description: "One of Norway's top courses located on the Fosen peninsula. Stunning coastal scenery.",
    udisc: "https://udisc.com/courses/orland-discgolfpark-ZBkU"
  },
  {
    name: "Dragvoll Discgolfpark",
    lat: 63.4100,
    lng: 10.4700,
    city: "Trondheim",
    region: "Trøndelag",
    holes: 18,
    rating: 3.8,
    reviews: 450,
    difficulty: "Moderate",
    description: "Popular course near NTNU campus in Trondheim.",
    udisc: ""
  },
  {
    name: "Estenstaddalen DGP",
    lat: 63.3900,
    lng: 10.3300,
    city: "Trondheim",
    region: "Trøndelag",
    holes: 18,
    rating: 4.0,
    reviews: 380,
    difficulty: "Hard",
    description: "Challenging forest course in the Trondheim area.",
    udisc: ""
  },
  {
    name: "Steinkjer Discgolfpark",
    lat: 64.0150,
    lng: 11.4950,
    city: "Steinkjer",
    region: "Trøndelag",
    holes: 18,
    rating: 3.7,
    reviews: 200,
    difficulty: "Moderate",
    description: "Nice course in the Steinkjer area.",
    udisc: ""
  },
  {
    name: "Namsos Discgolfbane",
    lat: 64.4667,
    lng: 11.5000,
    city: "Namsos",
    region: "Trøndelag",
    holes: 18,
    rating: 3.5,
    reviews: 150,
    difficulty: "Moderate",
    description: "Course in the Namdal region of Trøndelag.",
    udisc: ""
  },
  {
    name: "Røros Discgolfbane",
    lat: 62.5733,
    lng: 11.3833,
    city: "Røros",
    region: "Trøndelag",
    holes: 18,
    rating: 3.9,
    reviews: 220,
    difficulty: "Moderate",
    description: "Mountain course near the UNESCO World Heritage town of Røros.",
    udisc: ""
  },
  {
    name: "Oppdal Discgolfbane",
    lat: 62.5933,
    lng: 9.6917,
    city: "Oppdal",
    region: "Trøndelag",
    holes: 18,
    rating: 4.1,
    reviews: 280,
    difficulty: "Moderate",
    description: "Beautiful mountain course near the ski resort town of Oppdal.",
    udisc: ""
  },

  // === Nord-Norge (Northern Norway) ===
  {
    name: "Bodø Discgolfpark",
    lat: 67.2800,
    lng: 14.4050,
    city: "Bodø",
    region: "Nordland",
    holes: 18,
    rating: 4.0,
    reviews: 300,
    difficulty: "Moderate",
    description: "Northernmost major disc golf course. Midnight sun rounds in summer!",
    udisc: ""
  },
  {
    name: "Lurøya Discgolfbane",
    lat: 66.4167,
    lng: 12.9833,
    city: "Lurøy",
    region: "Nordland",
    holes: 9,
    rating: 4.2,
    reviews: 120,
    difficulty: "Easy",
    description: "Scenic island course in Nordland. Easy and family-friendly with stunning coastal views.",
    udisc: ""
  },
  {
    name: "Mo i Rana Discgolfpark",
    lat: 66.3133,
    lng: 14.1417,
    city: "Mo i Rana",
    region: "Nordland",
    holes: 18,
    rating: 3.7,
    reviews: 180,
    difficulty: "Moderate",
    description: "Course near the Arctic Circle in Mo i Rana.",
    udisc: ""
  },
  {
    name: "Tromsø Discgolfpark",
    lat: 69.6489,
    lng: 18.9551,
    city: "Tromsø",
    region: "Troms og Finnmark",
    holes: 18,
    rating: 3.9,
    reviews: 250,
    difficulty: "Moderate",
    description: "Arctic disc golf in the 'Gateway to the Arctic'. Play under the midnight sun!",
    udisc: ""
  },
  {
    name: "Harstad Discgolfbane",
    lat: 68.7983,
    lng: 16.5367,
    city: "Harstad",
    region: "Troms og Finnmark",
    holes: 18,
    rating: 3.6,
    reviews: 140,
    difficulty: "Moderate",
    description: "Course on the island of Hinnøya near Harstad.",
    udisc: ""
  },
  {
    name: "Narvik Discgolfbane",
    lat: 68.4283,
    lng: 17.4267,
    city: "Narvik",
    region: "Nordland",
    holes: 18,
    rating: 3.7,
    reviews: 160,
    difficulty: "Moderate",
    description: "Mountain course in Narvik with dramatic fjord scenery.",
    udisc: ""
  },
  {
    name: "Sortland Discgolfpark",
    lat: 68.6933,
    lng: 15.4133,
    city: "Sortland",
    region: "Nordland",
    holes: 18,
    rating: 3.5,
    reviews: 120,
    difficulty: "Moderate",
    description: "Course in the 'Blue City' of Vesterålen.",
    udisc: ""
  },
  {
    name: "Alta Discgolfbane",
    lat: 69.9683,
    lng: 23.2717,
    city: "Alta",
    region: "Troms og Finnmark",
    holes: 18,
    rating: 3.8,
    reviews: 160,
    difficulty: "Moderate",
    description: "One of the northernmost disc golf courses in the world. Northern lights rounds in winter!",
    udisc: ""
  },
  {
    name: "Hammerfest Discgolfbane",
    lat: 70.6634,
    lng: 23.6821,
    city: "Hammerfest",
    region: "Troms og Finnmark",
    holes: 9,
    rating: 3.4,
    reviews: 80,
    difficulty: "Easy",
    description: "One of the world's northernmost disc golf courses in Hammerfest.",
    udisc: ""
  },
  {
    name: "Lofoten Discgolfbane",
    lat: 68.2350,
    lng: 14.5683,
    city: "Svolvær",
    region: "Nordland",
    holes: 18,
    rating: 4.1,
    reviews: 200,
    difficulty: "Moderate",
    description: "Spectacular course in the Lofoten Islands with dramatic mountain and sea views.",
    udisc: ""
  },

  // === More Østlandet courses ===
  {
    name: "Notodden Discgolfpark",
    lat: 59.5567,
    lng: 9.2583,
    city: "Notodden",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 3.8,
    reviews: 220,
    difficulty: "Moderate",
    description: "Course near the industrial heritage town of Notodden.",
    udisc: ""
  },
  {
    name: "Skien Discgolfpark",
    lat: 59.2100,
    lng: 9.6100,
    city: "Skien",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 3.7,
    reviews: 280,
    difficulty: "Moderate",
    description: "Popular course in the Skien area.",
    udisc: ""
  },
  {
    name: "Porsgrunn Discgolfbane",
    lat: 59.1400,
    lng: 9.6567,
    city: "Porsgrunn",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 3.6,
    reviews: 200,
    difficulty: "Moderate",
    description: "Nice course in Porsgrunn.",
    udisc: ""
  },
  {
    name: "Hønefoss Discgolfpark",
    lat: 60.1700,
    lng: 10.2567,
    city: "Hønefoss",
    region: "Viken",
    holes: 18,
    rating: 3.7,
    reviews: 220,
    difficulty: "Moderate",
    description: "Course near Hønefoss in the Ringerike area.",
    udisc: ""
  },
  {
    name: "Jessheim Discgolfpark",
    lat: 60.1467,
    lng: 11.1717,
    city: "Jessheim",
    region: "Viken",
    holes: 18,
    rating: 3.6,
    reviews: 250,
    difficulty: "Moderate",
    description: "Accessible course near Oslo Airport Gardermoen.",
    udisc: ""
  },
  {
    name: "Skåla DiskGolfPark",
    lat: 61.8367,
    lng: 6.9500,
    city: "Skåla",
    region: "Møre og Romsdal",
    holes: 18,
    rating: 4.3,
    reviews: 280,
    difficulty: "Hard",
    description: "Mountain course near Skåla with spectacular scenery.",
    udisc: ""
  },
  {
    name: "Liarlund Diskgolf",
    lat: 59.8600,
    lng: 10.8000,
    city: "Lørenskog",
    region: "Viken",
    holes: 9,
    rating: 3.5,
    reviews: 350,
    difficulty: "Easy",
    description: "Easy 9-hole course near Oslo. Great for beginners and families.",
    udisc: ""
  },
  {
    name: "Ås Discgolfpark",
    lat: 59.6600,
    lng: 10.7900,
    city: "Ås",
    region: "Viken",
    holes: 18,
    rating: 3.7,
    reviews: 280,
    difficulty: "Moderate",
    description: "Course near NMBU university campus in Ås.",
    udisc: ""
  },
  {
    name: "Sarpsborg Discgolfbane",
    lat: 59.2833,
    lng: 11.1133,
    city: "Sarpsborg",
    region: "Viken",
    holes: 18,
    rating: 3.6,
    reviews: 220,
    difficulty: "Moderate",
    description: "Course in the Sarpsborg area of Østfold.",
    udisc: ""
  },
  {
    name: "Rjukan Discgolfbane",
    lat: 59.8783,
    lng: 8.5933,
    city: "Rjukan",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 4.0,
    reviews: 180,
    difficulty: "Hard",
    description: "Mountain course in the Rjukan valley, UNESCO industrial heritage area.",
    udisc: ""
  },
  {
    name: "Gjøvik Olympiske Discgolf",
    lat: 60.8000,
    lng: 10.7000,
    city: "Gjøvik",
    region: "Innlandet",
    holes: 9,
    rating: 3.4,
    reviews: 150,
    difficulty: "Easy",
    description: "Easy 9-hole course near Gjøvik Olympic Cavern Hall.",
    udisc: ""
  },
  {
    name: "Eidsvoll Discgolfbane",
    lat: 60.3300,
    lng: 11.2500,
    city: "Eidsvoll",
    region: "Viken",
    holes: 18,
    rating: 3.5,
    reviews: 200,
    difficulty: "Moderate",
    description: "Course near the historic Eidsvoll building.",
    udisc: ""
  },
  {
    name: "Ringebu Discgolfpark",
    lat: 61.5183,
    lng: 10.1667,
    city: "Ringebu",
    region: "Innlandet",
    holes: 18,
    rating: 3.8,
    reviews: 200,
    difficulty: "Moderate",
    description: "Scenic course in Gudbrandsdalen valley.",
    udisc: ""
  },
  {
    name: "Dombås Discgolfbane",
    lat: 62.0733,
    lng: 9.1250,
    city: "Dombås",
    region: "Innlandet",
    holes: 18,
    rating: 3.9,
    reviews: 180,
    difficulty: "Moderate",
    description: "Mountain course at the junction of Gudbrandsdalen and Romsdalen.",
    udisc: ""
  },
  {
    name: "Otta Discgolfpark",
    lat: 61.7717,
    lng: 9.5383,
    city: "Otta",
    region: "Innlandet",
    holes: 18,
    rating: 3.7,
    reviews: 160,
    difficulty: "Moderate",
    description: "Course near Otta in the heart of Gudbrandsdalen.",
    udisc: ""
  },
  {
    name: "Vinstra Discgolfbane",
    lat: 61.5883,
    lng: 9.9683,
    city: "Vinstra",
    region: "Innlandet",
    holes: 9,
    rating: 3.4,
    reviews: 120,
    difficulty: "Easy",
    description: "Easy course in the Peer Gynt country near Vinstra.",
    udisc: ""
  },
  {
    name: "Fagernes Discgolfpark",
    lat: 60.9850,
    lng: 9.2333,
    city: "Fagernes",
    region: "Innlandet",
    holes: 18,
    rating: 3.8,
    reviews: 200,
    difficulty: "Moderate",
    description: "Course in the Valdres region near Fagernes.",
    udisc: ""
  },
  {
    name: "Beitostølen Discgolfbane",
    lat: 61.2517,
    lng: 8.9117,
    city: "Beitostølen",
    region: "Innlandet",
    holes: 18,
    rating: 4.2,
    reviews: 250,
    difficulty: "Hard",
    description: "Mountain resort course at Beitostølen with stunning Jotunheimen views.",
    udisc: ""
  },
  {
    name: "Geilo Discgolfpark",
    lat: 60.5333,
    lng: 8.2050,
    city: "Geilo",
    region: "Viken",
    holes: 18,
    rating: 4.1,
    reviews: 280,
    difficulty: "Moderate",
    description: "Mountain resort course at Geilo, between Oslo and Bergen.",
    udisc: ""
  },
  {
    name: "Gol Discgolfbane",
    lat: 60.7017,
    lng: 8.9467,
    city: "Gol",
    region: "Viken",
    holes: 18,
    rating: 3.7,
    reviews: 180,
    difficulty: "Moderate",
    description: "Course in the Hallingdal valley near Gol.",
    udisc: ""
  },
  {
    name: "Hemsedal Discgolfbane",
    lat: 60.8600,
    lng: 8.5600,
    city: "Hemsedal",
    region: "Viken",
    holes: 18,
    rating: 4.0,
    reviews: 220,
    difficulty: "Moderate",
    description: "Course in the 'Scandinavian Alps' at Hemsedal ski resort.",
    udisc: ""
  },

  // === Stavanger area ===
  {
    name: "Sandnes Discgolfpark",
    lat: 58.8517,
    lng: 5.7350,
    city: "Sandnes",
    region: "Rogaland",
    holes: 18,
    rating: 3.8,
    reviews: 250,
    difficulty: "Moderate",
    description: "Course in Sandnes near Stavanger.",
    udisc: ""
  },

  // === More Northern courses ===
  {
    name: "Vesterålen Discgolfpark",
    lat: 68.7967,
    lng: 15.6083,
    city: "Stokmarknes",
    region: "Nordland",
    holes: 18,
    rating: 3.7,
    reviews: 130,
    difficulty: "Moderate",
    description: "Scenic island course in the Vesterålen archipelago.",
    udisc: ""
  },
  {
    name: "Mosjøen Discgolfbane",
    lat: 65.8350,
    lng: 13.1900,
    city: "Mosjøen",
    region: "Nordland",
    holes: 18,
    rating: 3.6,
    reviews: 140,
    difficulty: "Moderate",
    description: "Course in the historic wooden town of Mosjøen.",
    udisc: ""
  },
  {
    name: "Sandnessjøen Discgolfbane",
    lat: 66.0200,
    lng: 12.6300,
    city: "Sandnessjøen",
    region: "Nordland",
    holes: 18,
    rating: 3.5,
    reviews: 110,
    difficulty: "Moderate",
    description: "Helgeland coast course with views of the Seven Sisters mountain range.",
    udisc: ""
  },
  {
    name: "Brønnøysund Discgolfbane",
    lat: 65.4750,
    lng: 12.2100,
    city: "Brønnøysund",
    region: "Nordland",
    holes: 9,
    rating: 3.4,
    reviews: 80,
    difficulty: "Easy",
    description: "Coastal course near Torghatten, the mountain with a hole through it.",
    udisc: ""
  },
  {
    name: "Levanger Discgolfbane",
    lat: 63.7467,
    lng: 11.3000,
    city: "Levanger",
    region: "Trøndelag",
    holes: 18,
    rating: 3.6,
    reviews: 180,
    difficulty: "Moderate",
    description: "Course in the wooden town of Levanger.",
    udisc: ""
  },
  {
    name: "Verdal Discgolfbane",
    lat: 63.7917,
    lng: 11.4833,
    city: "Verdal",
    region: "Trøndelag",
    holes: 18,
    rating: 3.5,
    reviews: 150,
    difficulty: "Moderate",
    description: "Course in the Verdal area of Trøndelag.",
    udisc: ""
  },
  {
    name: "Stjørdal Discgolfpark",
    lat: 63.4700,
    lng: 10.9200,
    city: "Stjørdal",
    region: "Trøndelag",
    holes: 18,
    rating: 3.7,
    reviews: 200,
    difficulty: "Moderate",
    description: "Course near Trondheim Airport Værnes.",
    udisc: ""
  },
  {
    name: "Orkanger Discgolfbane",
    lat: 63.3000,
    lng: 9.8467,
    city: "Orkanger",
    region: "Trøndelag",
    holes: 18,
    rating: 3.6,
    reviews: 170,
    difficulty: "Moderate",
    description: "Course in the Orkla valley.",
    udisc: ""
  },
  {
    name: "Stokke Discgolfpark",
    lat: 59.2283,
    lng: 10.3000,
    city: "Stokke",
    region: "Vestfold og Telemark",
    holes: 18,
    rating: 3.7,
    reviews: 200,
    difficulty: "Moderate",
    description: "Well-maintained course in the Stokke area.",
    udisc: ""
  },
  {
    name: "Mandal Discgolfbane",
    lat: 58.0283,
    lng: 7.4583,
    city: "Mandal",
    region: "Agder",
    holes: 18,
    rating: 3.7,
    reviews: 180,
    difficulty: "Moderate",
    description: "Course near Norway's southernmost city with coastal scenery.",
    udisc: ""
  },
  {
    name: "Flekkefjord Discgolfbane",
    lat: 58.2967,
    lng: 6.6633,
    city: "Flekkefjord",
    region: "Agder",
    holes: 9,
    rating: 3.5,
    reviews: 100,
    difficulty: "Easy",
    description: "Coastal course in the town of Flekkefjord.",
    udisc: ""
  },
  {
    name: "Lyngdal Discgolfbane",
    lat: 58.1367,
    lng: 7.0717,
    city: "Lyngdal",
    region: "Agder",
    holes: 18,
    rating: 3.6,
    reviews: 150,
    difficulty: "Moderate",
    description: "Southern Norwegian course near Lyngdal.",
    udisc: ""
  },
  {
    name: "Farsund Discgolfbane",
    lat: 58.0950,
    lng: 6.8050,
    city: "Farsund",
    region: "Agder",
    holes: 9,
    rating: 3.4,
    reviews: 90,
    difficulty: "Easy",
    description: "Southernmost disc golf course area with coastal charm.",
    udisc: ""
  }
];
